apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: pablitorub/ad-node:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          volumeMounts:
            - name: node-persistent-storage
              mountPath: /app/uploads/images
            - name: cert
              mountPath: /app/cert
          env:
            - name: USR
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: USR
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: PASS
            - name: SERVER
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: SERVER
      volumes:
        - name: node-persistent-storage
          persistentVolumeClaim:
            claimName: node-pvc
        - name: cert
          secret:
            secretName: cert