apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-pvc
  labels:
    app: node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard